name: 构建安装包

on:
  workflow_dispatch:
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Environmental_installation
        run: sudo apt install apktool signapk openjdk-8-jdk
             sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
      - uses: actions/checkout@v3
      - name: build-apk
        run: ./build.sh
