name: 构建安装包

on:
  workflow_dispatch:
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install -y openjdk-8-jdk
          sudo apt-get install -y apktool
          sudo apt-get install -y signapk
      - name: Set Java version
        run: |
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-openjdk-amd64/bin/java 1000
          sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/bin/java
          sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac 1000
          sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
      - name: Configure environment variables
        run: |
          echo "export ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
      - name: build-apk
        run: |
          cd mybv/java
          chmod u+x /build.sh
          ./build.sh
          cd ../..
          apktool b -c --use-aapt2 mybv
          signapk platform.x509.pem platform.pk8 ./mybv/dist/mybv.apk mybv.apk
