name: 构建安装包

on:
  workflow_dispatch:
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install -y openjdk-8-jdk
          sudo apt-get install -y apktool
          sudo apt-get install -y signapk
      - name: Set Java version
        run: |
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-openjdk-amd64/bin/java 1000
          sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/bin/java
          sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac 1000
          sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
      - name: Configure environment variables
        run: |
          echo "export ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
      - name: build-apk
        run: |
          cd mybv/java
          #d2j-dex2jar --force ../../bv0/build/apk/classes.dex
          rm $(find classes -name *.class)
          javac -Xdiags:verbose -classpath 'classes-dex2jar.jar:android.jar' $(find classes -name *.java)
          rm $(find classes/com/bilibili/tv -name R\$*.class)
          rm classes/com/bilibili/tv/R.class
          rm classes/bl/u.class
          java -jar dx.jar --dex --output=out.dex classes
          java -jar baksmali-2.5.2.jar d out.dex -l -o ../smali
          cd ../..
          apktool b -c --use-aapt2 mybv
          signapk platform.x509.pem platform.pk8 ./mybv/dist/mybv.apk mybv.apk
